[programs.print_foo]
command = "/bin/bash"
#args = ["-c", "while true; do echo 'foo'; sleep 1; done"]
args = ["-c", "sleep 2; exit 1;"]
autostart = false

[programs.print_bar]
command = "/bin/bash"
args = ["-c", "while true; do echo 'bar'; sleep 1; done"]
